# Environmetal variables that are needed for TACOPLAY are defined here.
# This file contains variables for mutiple playbooks: TACOPLAY, Ceph-Ansible, Kubespray.
# Please make sure to check what variable belongs to what playbook before you look up further details. 
#
# Define only what you need in this file. For more options, please check vars/site-specific.yml. 
# Also check out the official TACOPLAY documentation for related information.
# https://taco-docs.readthedocs.io/ko/latest/tacoplay/tacoplay.html#playbooks
# 
# Section 1 - Repository

# cicd_registry_enabled : false 
# // This is a varaible of TACOPLAY
# // set it to 'true' only if you have access to TACO team;s CI/CD registry. Regular users do not need this option.  
cicd_registry_enabled: false

# localrepo_enabled: false
# // This is a varaible of TACOPLAY
# // set it to 'true' if you want TACOPLAY to utilize a local repository instead of a public one.
localrepo_enabled: false

# localrepo_yum: 
# // This is a varaible of TACOPLAY
# // specify the address of the local Yum repository 

# localrepo_k8s:
# // This is a varaible of TACOPLAY
# // specify the address of the local K8S repository

# localrepo_pypi:
# // This is a varaible of TACOPLAY
# // specify the address of the local Pypi repository

# docker_insecure_registries: "192.168.201.4:5000"
# // This is a varaible of TACOPLAY
# // If you have any insecure registry, add it to the list. Not recommended for production environment.
docker_insecure_registries: ""






# Section 2 - Ceph
# varaibles below are ONLY REQUIRED when you have a pre-installed Ceph cluster.
# Please comment out below 3 variables and skip to the part if you intend to install a Ceph cluster through TACOPLAY.
# For further details, please refer to var/site_specific.yml

# ceph_monitors: 192.168.204.49, 192.168.204.50
# // This is a varaible of TACOPLAY
# // Enter address(es) of ceph-mon that you already installed.  
ceph_monitors: 

# ceph_admin_keyring: AQB+kgtbKsHZExAAPz/
# // This is a varaible of TACOPLAY
# // Enter the admin keyring value of your ceph cluster
ceph_admin_keyring: 


# taco_storage: rbd
# // This is a varaible of TACOPLAY
# //backend storage type for K8S cluster. Defaults to rbd.
taco_storage:


# variables below are ONLY REQUIRED when you install a Ceph cluster through TACOplay.
# Please comment out the variables below if you already have a ceph cluster.

# monitor_interface: bond0
# // This is a variable of Ceph-Ansible
# // Specify a network interface on your ceph nodes that ceph-mon will use.
monitor_interface:

# public_network: 147.75.94.0/24
# // This is a variable of Ceph-Ansible. 
# // Specify a CIDR for Ceph public network. Network interfaces on your nodes will automatically be selected with this information.
public_network:

# cluster_network: 147.75.94.0/24
# // This is a variable of Ceph-Ansible. 
# // Specify a CIDR for Ceph public network. Network interfaces on your nodes will automatically be selected with this information.


# osd_objectstore:  bluestore
# // This is a variable of Ceph-Ansible.
# // Choose an objectstore type for OSDs

# lvm_volumes: 
#   - data: /dev/sda
#   - data: /dev/sdb
#
# // This is a variable of Ceph-Ansible.
# // specify block storage devices used for objectstore.


# ceph_conf_overrides:
#   global:
#     mon_allow_pool_delete: true
#     osd_pool_default_size: 1
#     osd_pool_default_min_size: 1
#     osd_pg_stat_report_internal_max: 1
#   osd:
#     osd_min_pg_log_entries: 10
#     osd_max_pg_log_entries: 10
#     osd_pg_log_dups_tracked: 10
#     osd_pg_log_trim_min: 10
#
# // This is a variable of Ceph-Ansible.
# Specify any options that you want to override with for your ceph.conf
# Please refer to the official Ceph documentation for more options. 

ceph_conf_overrides:


# Section 3 - Creating Ceph pools for K8S and OpenStack 
# openstack_config: true
# // This is a variable of Ceph-Ansible. 
# // It determines whether you want to apply Ceph configuration, specific for OpenStack enviornment.
# // Set to true, if you want Ceph-Ansible to run a playbook so that you can use your ceph cluster for your OpenStack deployment.
# // Make sure to modify ceph pool definitions to your requirements.
# // Set to false if you don't plan to deploy OpenStack.

openstack_config:
# kube_pool:
#   name: "kube"
#   pg_num: 64
#   pgp_num: 64
#   rule_name: "replicated_rule"
#   type: 1
#   erasure_profile: ""
#   expected_num_objects: ""
#   application: "rbd"
# openstack_glance_pool:
#   name: "images"
#   pg_num: 64
#   pgp_num: 64
#   rule_name: "replicated_rule"
#   type: 1
#   erasure_profile: ""
#   expected_num_objects: ""
# openstack_cinder_pool:
#   name: "volumes"
#   pg_num: 64
#   pgp_num: 64
#   rule_name: "replicated_rule"
#   type: 1
#   erasure_profile: ""
#   expected_num_objects: ""
# openstack_cinder_backup_pool:
#   name: "backups"
#   pg_num: 2
#   pgp_num: 2
#   rule_name: "replicated_rule"
#   type: 1
#   erasure_profile: ""
#   expected_num_objects: ""
# openstack_nova_vms_pool:
#   name: "vms"
#   pg_num: 64
#   pgp_num: 64
#   rule_name: "replicated_rule"
#   type: 1
#   erasure_profile: ""
#   expected_num_objects: ""
#   application: "rbd"
#
# openstack_pools:
#   - "{{ kube_pool }}"
#   - "{{ openstack_glance_pool }}"
#   - "{{ openstack_cinder_pool }}"
#   - "{{ openstack_cinder_backup_pool }}"
#   - "{{ openstack_nova_vms_pool }}"



# Section 4 - Kubernetes
# Variables in this section mostly concerns installation of Kubernetes through Kubespray.

# kubectl_localhost: true
# //This is a variable of Kubespray
# // Set it to 'true' if you want to be able to run 'kubectl' from the node that TACOPLAY is run.
# // Set it to 'false' if you only want to be able to run 'kubectl' from K8S master nodes.
kubectl_localhost:

# kube_service_addresses: 10.233.0.0/18
# // This is a variable of Kubespray
# // Specify a CIDR for Service IPs of your K8S cluster.
kube_service_addresses:

# kube_pods_subnet: 10.233.64.0/18
# // This is a variable of Kubespray
# // Specify a CIDR for Pods of your K8S cluster.
kube_pods_subnet: 

# ipip_mode: Never
# // This is a variable of Kubespray
# // Kubespray uses Calico as a default CNI. This is an option for Calico. Please refer to the official documentation of Calico for more information.
# // Set it to "Always" if you want to use IP in IP mode in Calico. Usually recommended for cloud deployments
# // Set it to "Never" if you want to disable IP in IP mode in Calico. Usually recommended for On-premise deployments. 
ipip_mode: 

# peer_with_router: false
# // This is a variable of Kubespray
# // Kubespray uses Calico as a default CNI. This is an option for Calico. Please refer to the official documentation of Calico for more information.
# // Set it to "false" if you don't need to set up BGP routing in your environment.
# // Set it to "true" if you need to set up BGP in your enviornment.
peer_with_router: false

# kube_apiserver_insecure_bind_address: 0.0.0.0
# // This is a variable of Kubespray. 
# // Change to 0.0.0.0 to enable insecure access from anywhere (not recommended)
# // Defaults to 127.0.0.1 when commented out.
kube_apiserver_insecure_bind_address: 0.0.0.0



# kube_apiserver_insecure_port: 8090
# // This is a variable of Kubespray. 
# // Specify the port number you want to use for any insecure communication to kube_apiserver. 
# // Port 8090 is commonly used for this purpose.
# // If you want to disable insecure communication completely, set the port number to "0".
# // Defaults to 0 if commented out.
kube_apiserver_insecure_port:

# auto_release_enabled: true
# // This is a variable of TACOPLAY.
# // When set to "true", performs two extra actions regarding ingress controller and updating OpenStack information.
# // When set to "false", the two extra actions are ignored.
auto_release_enabled:

# os_root_user: admin
# // This is a variable of TACOPLAY.
# // Specify a string that will be used as a name of the root user for all OpenStack related databases and services 
os_root_user:

# os_root_password: password
# // This is a variable of TACOPLAY.
# // Specify a string that will be used as a name of the root password for all OpenStack related databases and services 
os_root_password: password
