---
- name: include global default variables
  import_playbook: include_defaults.yml

- name: setup host operating systems in taco host group
  hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: setup-os, tags: setup-os }
    - { role: container-registry/client, tags: setup-os }

# Add Ceph OSD
- import_playbook: ceph-ansible/infrastructure-playbooks/add-osd.yml
  tags: ceph
  when: taco_storage_backend == 'ceph'

# TODO: add tests for checking status of the new ceph cluster

# Tune system for OpenStack.
# We call this role before kubespray/scale so that the system could be ready
# before openstack pods are up and running
- hosts: controller-node:compute-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco-apps/openstack/setup-os, tags: openstack, when: '"openstack" in taco_apps' }

# Install K8S
- import_playbook: kubespray/scale.yml
  tags: k8s

# TODO: add tests for checking the status of the updated k8s cluster

# Delete sona-config POD for synchronizing node status to SONA
- hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco-apps/sona/refresh-config, tags: sona, when: sona_integration }
