docker_image_repo: "docker.io"
quay_image_repo: "quay.io"
ghcr_image_repo: "ghcr.io"

bin_dir: /usr/local/bin
decapod_enabled: true

decapod_bootstrap_source: "https://github.com/openinfradev/decapod-bootstrap.git"
decapod_bootstrap_dest: "{{ role_path }}/../../decapod/decapod-bootstrap"
decapod_bootstrap_version: "main"

decapod_base_source: "https://github.com/openinfradev/decapod-base-yaml.git"
decapod_base_dest: "{{ role_path }}/../../decapod/decapod-base-yaml"
decapod_base_version: "main"

decapod_site_source: "https://github.com/openinfradev/decapod-site"
decapod_site_dest: "{{ role_path }}/../../decapod/decapod-site"
decapod_site_version: "main"

decapod_flow_source: "https://github.com/openinfradev/decapod-flow.git"
decapod_flow_dest: "{{ role_path }}/../../decapod/decapod_flow"
decapod_flow_version: "main"

argo_version: "v2.12.5"
argo_client_binary_name: "argo-linux-amd64"
argo_client_url: "https://github.com/argoproj/argo-workflows/releases/download/{{ argo_version }}/{{ argo_client_binary_name }}.gz"

argocd_version: "v2.1.5"
argocd_chart_version: "3.26.3"
argocd_chart_source: "{{ role_path}}/../../charts/argo-cd"
argocd_client_binary_name: "argocd-linux-amd64"
argocd_client_url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/{{ argocd_client_binary_name }}"
