---
- name: backup current repository files
  import_tasks: backup_repo_files.yml
  when:
      pkg_repo_url != ""
  ignore_errors: yes

- name: set local repo urls
  import_tasks: set_repo_urls.yml
  when:
    - pkg_repo_url != "" or pip_repo_url != ""

- name: add local centos base repo
  template:
    src: local-centosbase.repo.j2
    dest: /etc/yum.repos.d/local-centosbase.repo
  when:
    - pkg_repo_url != ""
    - ansible_distribution in ["CentOS","RedHat"]

- name: add epel repo
  template:
    src: local-epel.repo.j2
    dest: /etc/yum.repos.d/local-epel.repo
  when:
    - pkg_repo_url != ""
    - ansible_distribution in ["CentOS","RedHat"]

- name: add docker repo
  template:
    src: local-docker.repo.j2
    dest: /etc/yum.repos.d/local-docker.repo
  when:
    - pkg_repo_url != ""
    - ansible_distribution in ["CentOS","RedHat"]

- name: add local ubuntu repo
  template:
    src: local-sources.list.j2
    dest: /etc/apt/sources.list
  when:
    - pkg_repo_url != ""
    - ansible_distribution in ["Ubuntu","Debian"]

- name: add local pypi repo
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
  when: pip_repo_url != ""

- name: update yum repository cache
  yum:
    update_cache: yes
  become: true
  vars:
    ansible_python_interpreter: "{{ /usr/bin/python }}"
  when:
    - ansible_distribution in ["CentOS","RedHat"]
    - "ansible_distribution_major_version | int == 7"

- name: update apt repository cache
  apt:
    update_cache: yes
  when:
    - ansible_distribution in ["Ubuntu", "Debian"]
